### ISSUE TITLE
Fails to find key in second object within array

### ISSUE THREAD

**Issue by andybonner** [BeAnMo/json-find#3]
Thanks for an awesome utility! I'm having an unexplained failure to find a certain key, though. In this example...
```
const doc1 = {
  "arr1": [
    {
      "arr2": [
        {
          "a": 1,
          "arrTarget": [
            {
              "b": 2
            },
            {
              "keyTarget": "target value"
            }
          ]
        }
      ]
    }
  ]
}
```
... `jsonFind(doc1).findValues("keyTarget")` returns an empty object. However, remove the object before the target object:
```
const doc2 = {
  "arr1": [
    {
      "arr2": [
        {
          "a": 1,
          "arrTarget": [
            {
              "keyTarget": "target value"
            }
          ]
        }
      ]
    }
  ]
}
```
... and it returns `target value` as expected. It also works when `{"keyTarget": "target value"}` is followed by another object.

**Comment by BeAnMo** [comment]
Thanks for the interest and catching the problem.

I updated findValues recently and left extra return statements in that didn't need to be there, which prevented full traversal of arrays. Now findValues works like it did prior to the recent patch.
