### ISSUE TITLE
Error: when value is null 

### ISSUE THREAD

**Issue by flftfqwxf** [BeAnMo/json-find#5]
json-find.js line:197

```
function isObject(v) {
    return typeof(v) === 'object' && !isArray(v);
}
```
modify:
```
function isObject(v) {
    return typeof(v) === 'object' && !isArray(v) && v !== null;
}
```

**Comment by BeAnMo** [comment]
Do you have an example of where this is causing an error?

**Comment by flftfqwxf** [comment]
@BeAnMo 

> const JsonFind = require('json-find');
> const a = {
>     "r": {
>         "b": "444",
>         "c": false,
>         "d": "555",
>         "e": null
>     }
> };
> let doc = JsonFind(a)
> let b =doc.findValues('b');
> console.log(b)

Error:

>  const allKeys = Object.keys(toSearchObj);
>                                ^
> 
> TypeError: Cannot convert undefined or null to object
>
